language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_BUILD_TOOLS_VERSION=26.0.1
    - ANDROID_ABI=armeabi-v7a

android:
 components:

 - tools

 - platform-tools

 - build-tools-$ANDROID_BUILD_TOOLS

 - android-$ANDROID_API

 - android-$EMULATOR_API_LEVEL

 - extra-google-m2repository

 - extra-android-m2repository # for design library

 - addon-google_apis-google-19 # google play services

 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL

 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

 licenses:

 - android-sdk-preview-license-.+

 - android-sdk-license-.+

 - google-gdk-license-.+

before_install:
  - echo yes | android update sdk --all --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION --no-ui --force

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-22 --abi $ANDROID_ABI
  - emulator -avd test -no-window &

script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

notifications:
  email:
    - thangtran480@gmail.com
